export const GET_AND_START_OBJECT_ANIMS = 'GET_AND_START_OBJECT_ANIMS';
export const PLAY_ALL = 'PLAY_ALL';
export const PAUSE_ALL = 'PAUSE_ALL';
export const SET_PLAYBACKRATE = 'SET_PLAYBACKRATE';
export const DECREASE_PLAYBACKRATE_AUTOMATICALLY = 'DECREASE_PLAYBACKRATE_AUTOMATICALLY';